name: Install AWS Session Manager plugin
description: Install AWS Session Manager plugin for the AWS CLI on linux runners
branding:
  icon: package
  color: blue
inputs:
  cache:
    description: Cache the downloaded installer
    required: false
    default: true
runs:
  using: composite
  steps:
    - name: Check if pre-installed
      id: ssm-binary-check
      shell: bash
      run: "$GITHUB_ACTION_PATH/scripts/verify.sh"

    - name: Cache or Restore the installer
      if: ${{ inputs.cache == 'true' && steps.ssm-binary-check.outputs.AWS_SESSION_MANAGER_PREINSTALLED == 'false' }}
      uses: actions/cache@v4
      id: aws-ssm-cache
      with:
        path: |
          ${{ runner.temp }}/aws-ssm-cache/*.deb
          ${{ runner.temp }}/aws-ssm-cache/*.rpm
        key: ${{ runner.os }}-${{ runner.arch }}-aws-ssm-cache-v1

    - name: Install Session manager plugin
      if: ${{ steps.ssm-binary-check.outputs.AWS_SESSION_MANAGER_PREINSTALLED == 'false' }}
      env:
        CACHE_HIT: ${{ steps.aws-ssm-cache.outputs.cache-hit == 'true' }}
        CACHE_ENABLED: ${{ inputs.cache == 'true'}}
        CACHE_PATH: ${{ runner.temp }}/aws-ssm-cache
      shell: bash
      run: "$GITHUB_ACTION_PATH/scripts/install.sh"