name: tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 16 * *'
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  if-does-not-exist:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        cache: [ true, false ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove plugin if installed
        run: |
          sudo apt remove --purge -y session-manager-plugin
          sudo rm -f /usr/local/bin/session-manager-plugin          

      - name: "Execute this action, cache=${{ matrix.cache }}"
        uses: ./
        with:
          cache: ${{ matrix.cache }}

  if-already-exists:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute this action
        uses: ./